version: '3.8'
services:
  php:
    build:
      context: ./docker/php
    container_name: php
    volumes:
      - ./:/var/www/html
    user: "${UID}:${GID}"
    networks:
      - weather_app
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - weather_app
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: '${ROOT_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    command:
        - --default-authentication-plugin=mysql_native_password
        - --bind-address=0.0.0.0
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./:/home
      - mysql-data:/var/lib/mysql
    networks:
      - weather_app
networks:
  weather_app:
    driver: bridge
volumes:
  mysql-data:
